export const FETCH_DATA_REQUEST_BS = "FETCH_DATA_REQUEST_BS";
export const FETCH_DATA_SUCCESS_BS = "FETCH_DATA_SUCCESS_BS";
export const FETCH_DATA_FAILURE_BS = "FETCH_DATA_FAILURE_BS";

export const FETCH_DATA_REQUEST_SW = "FETCH_DATA_REQUEST_SW";
export const FETCH_DATA_SUCCESS_SW = "FETCH_DATA_SUCCESS_SW";
export const FETCH_DATA_FAILURE_SW = "FETCH_DATA_FAILURE_SW";

export const FETCH_DATA_REQUEST_TWIRED = "FETCH_DATA_REQUEST_TWIRED";
export const FETCH_DATA_SUCCESS_TWIRED = "FETCH_DATA_SUCCESS_TWIRED";
export const FETCH_DATA_FAILURE_TWIRED = "FETCH_DATA_FAILURE_TWIRED";

export const FETCH_DATA_REQUEST_TWIRELESS = "FETCH_DATA_REQUEST_TWIRELESS";
export const FETCH_DATA_SUCCESS_TWIRELESS = "FETCH_DATA_SUCCESS_TWIRELESS";
export const FETCH_DATA_FAILURE_TWIRELESS = "FETCH_DATA_FAILURE_TWIRELESS";

export const FETCH_DATA_REQUEST_THEDPHONES = "FETCH_DATA_REQUEST_THEDPHONES";
export const FETCH_DATA_SUCCESS_THEDPHONES = "FETCH_DATA_SUCCESS_THEDPHONES";
export const FETCH_DATA_FAILURE_THEDPHONES = "FETCH_DATA_FAILURE_THEDPHONES";

export const FETCH_DATA_REQUEST_GAMING = "FETCH_DATA_REQUEST_GAMING";
export const FETCH_DATA_SUCCESS_GAMING = "FETCH_DATA_SUCCESS_GAMING";
export const FETCH_DATA_FAILURE_GAMING = "FETCH_DATA_FAILURE_GAMING";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
